all:
	GOARCH=amd64 GOAMD64=v3 go run -mod=readonly main.go DE ../../data/germany-latest.osm.pbf
de:
	GOARCH=amd64 GOAMD64=v3 go run -mod=readonly main.go DE ../../data/germany-latest.osm.pbf
fr:
	GOARCH=amd64 GOAMD64=v3 go run -mod=readonly main.go FR ../../data/germany-latest.osm.pbf
